package cognizant.number;

import java.util.Arrays;

/**
 * 📝 Problem: Special Sequence Generator
 *
 * Problem Statement:
 * You are given the first six terms of a sequence. Starting from the 7th term,
 * each new term is generated by adding the two most recent terms.
 * Return an array representing the first N terms of the sequence.
 *
 * Input Specification:
 * input1 : An integer value N
 * input2 : An integer array S of size 6
 *
 * Output Specification:
 * Return an integer array of size N.
 */

public class SequenceGenerator {
    public static int[] generateSequence(int N, int[] arr) {
        int a[] = new int[N];
        for(int i=0; i < arr.length; i++){
            a[i]=arr[i];
        }
        for (int i=arr.length;i < a.length; i++){
            a[i]=a[i-1]+a[i-2];
        }
        return a;
    }
        public static void main(String[] args) {
            // Test Case 1 (From Image)
            int input1 = 10;
            int[] input2 = {1, 2, 3, 4, 5, 6};

            System.out.println("--- Test Case 1 ---");
            System.out.println("Input N: " + input1);
            System.out.println("Input S: " + Arrays.toString(input2));

            int[] output = generateSequence(input1, input2);
            System.out.println("Output : " + Arrays.toString(output));
            // Expected Output: [1, 2, 3, 4, 5, 6, 11, 17, 28, 45]
        }
    }
